### PR TITLE
MNT:Nicer command line args. Standardizing the names

### PR DESCRIPTION
**Pull request by arkilic**
attn @hhslepicka

### CODE REVIEW

**Comment by arkilic** [comment]
https://github.com/NSLS-II/metadataclient/pull/16

**Comment by hhslepicka** [comment]
@arkilic you need to also change on ignition to accept the new parameters! ;) Travis is not happy with you! :stuck_out_tongue:

**Comment by hhslepicka** [comment]
PS: 👍  for the nicer cmd line args and for the standard.

**Comment by hhslepicka** [comment]
The server output at travis is:

```
cat nohup.out
usage: startup.py [-h] [--database DATABASE] [--mongohost MONGOHOST]
                  [--timezone TIMEZONE] [--mongoport MONGOPORT]
                  [--serviceport SERVICEPORT] [--tzone TIMEZONE]
startup.py: error: unrecognized arguments: --mongo-host localhost --mongo-port 27017 --service-port 7778
```

**Comment by arkilic** [comment]
hmmmmmm, not sure if this has picked up the metadataservice from master. I did not have to do that locally

**Comment by arkilic** [comment]
This is happening because you have not merged the metadataservice PR that is passing the tests yet.

**Comment by arkilic** [comment]
@hhslepicka Told ya :hamburger:

**Comment by hhslepicka** [comment]
Yep, you are right! Travis is happy again.
Merging now this magnificent work! 👍 
PS: 👎  for my stupid comment and not checking the metadataservice PR dependency.

**Comment by arkilic** [comment]
@hhslepicka travis is never happy. look at that face

**Pull request merged**
