### PR TITLE
MNT:Per discussion with @danielballan, goodbye "custom"

### PR DESCRIPTION
**Pull request by arkilic**
attn @tacaswell

### CODE REVIEW

**Comment by tacaswell** [comment]
run_stop should get the special casing that run_start gets

**Comment by arkilic** [comment]
I noticed that but was not sure if special casing was a good idea.

**Comment by ericdill** [comment]
Sorry about the codecov thing.  I just turned it off for this repo

**Comment by arkilic** [comment]
No worries, thx @ericdill

**Comment by arkilic** [comment]
@tacaswell @hhslepicka

**Comment by hhslepicka** [comment]
Sounds good for me! :+1:

**Comment by klauer** [comment]
:+1: so long, `custom`

**Comment by arkilic** [comment]
@klauer did we get rid off it in bluesky? I think it might still be somewhere in there

**Comment by tacaswell** [comment]
This is not _completely_ back compatible because it will fail on a positional `custom` input.

**Comment by klauer** [comment]
https://github.com/NSLS-II/bluesky/blob/master/bluesky/register_mds.py#L31

**Pull request merged**
